name: Build & Publish Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
        with:
            fetch-depth: 0
            fetch-tags: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          chmod u+x ./gradlew
          ./gradlew assembleRelease
      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Move APK
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} nga.apk
      - name: Upload APK to Github
        uses: actions/upload-artifact@v4
        with:
          name: nga
          path: "*.apk"

      - name: Generate Changelog
        id: generate_changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: Night-stars-1/changelog-generator-action@main

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.0.4
        with:
          name: NGA ${{ github.ref_name }}
          body:  ${{ steps.generate_changelog.outputs.changelog }}
          make_latest: true
          files: "*.apk"
